% function [L,S] = lumpX
clear all;

fname01 = 'ocean.QU.240km.151209.nc';
F.IRFdir = './';
F.irf_mask_dir = './';
F.IRFfile = fname01;
F.resolution = '240km_dst';
GRD01 = buildGRD(F,1);
fname02 = 'ocean.EC30to60E2r2.210210.nc';
F.IRFfile = fname02;
F.resolution = '60km_src';
GRD02 = buildGRD(F,1);

[mask01,vol01] = getmask(fname01);
[mask02,vol02] = getmask(fname02);
iwt01 = find(mask01==1);
iwt02 = find(mask02==1);

Wc = d0(vol01(iwt01));
Wf = d0(vol02(iwt02));

% load rgd.mat generated by ESMF_RegridWeightGen
load rgd2.mat;
Si = sparse(double(rgd.row(:)),double(rgd.col(:)),rgd.S(:),double(rgd.n_b),double(rgd.n_a));

FC = [];
for i = 1: size(mask01,2) 
  iocn01 = find(mask01(:,i)==1); % destination grid
  iocn02 = find(mask02(:,i)==1); % source grid
  St = (Si(:,iocn01))';
  Sf = (St(:,iocn02))';
  FC = blkdiag(FC,Sf);
end

S = Wf\(FC*Wc);
CF = FC';
L = Wc\(CF*Wf);

% end % for function lumpX

function [MASK,vol] = getmask(fname)
   KMT = ncread(fname,'maxLevelCell',[1],[inf]);
   temperature = ncread(fname,'temperature',[1 1 1],[inf inf inf]);
   AC = ncread(fname,'areaCell',[1],[inf]);
   DZT = ncread(fname,'restingThickness',[1 1],[inf inf]);
   vol = repmat(AC,[1 60]).*DZT';
   [nz,ny] = size(temperature);
   MASK = zeros(ny,nz);
   % keyboard
   for k = 1:nz
     MASK(:,k) = (k <= KMT(:));
   end % all k's 
end  % function getmask
